---

version: '3'

services:
  app:
    image: "darkthirtysecurity/gvmfeed:latest"
    hostname: "gvmfeed"
    restart: always
    ports:
      - "873:873"
    volumes:
      - "data:/data"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  data:
