---

version: '3'

services:
  app:
    image: "dgiorgio/gvm-feed-server:latest"
    hostname: "gvm-feed-server"
    restart: always
    ports:
      - "873:873"
    volumes:
      - "data:/data"
      - "/etc/localtime:/etc/localtime:ro"

volumes:
  data:
